let num1= 10;
let num2= 10;
let soma= num1 + num2;
console.log(soma);
let subtraçao= num1 - num2;
console.log(subtraçao);
let multiplicaçao= num1 * num2;
console.log(multiplicaçao);
let divisao = num1 / num2;
console.log(divisao);
